name: ESP-IDF Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IDF_TARGET: esp32s3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          target: esp32s3
