name: ESP-IDF Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IDF_TARGET: esp32s3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: v5.1.2

      - name: Build firmware
        run: idf.py build
